In [1]:
# Numerical Python lib.(Numpy). This lib is used to work with numerical data. It contains multidimensional array 
# and matrix data structure.It used to perform mathematical operation on array.It perform efficent calculation with array 
# and matrics.perform high level mathematical operation on array and matrices.

In [2]:
# Why use numpy??
# In python we have list which perform the same function as array but we use numpy because numpy array calculation 
# is 50x faster than list.

In [3]:
# Numpy array are stored at one continuos place in the memory, so processes can access and manupulate them very efficently. 
# This is called as locality of reference that is why numpy is faster than list.

In [3]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5])     # list pass in argument
print(arr)
print(type(arr))                  # ndarray:- 

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr1 = np.array((1,2,3,4,5))
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Dimension in array

In [7]:
arr2 = np.array(20)
print(arr2)
print(type(arr2))
print(arr2.ndim)    # gives dimension 

20
<class 'numpy.ndarray'>
0


In [8]:
arr3 = np.array([20,30,40,50])   # 1D array
print(arr3)
print(arr3.ndim)

[20 30 40 50]
1


In [9]:
arr4 = np.array([[1,2,3],[4,5,6]])   # 2D array
print(arr4)
print(arr4.ndim)

[[1 2 3]
 [4 5 6]]
2


In [10]:
arr5 = np.array([[[1,2,3,4],[5,6,7,8],[3,4,5,6],[5,6,7,8],[7,8,2,1]]])   # 3D array
print(arr5)
print(arr5.ndim)

[[[1 2 3 4]
  [5 6 7 8]
  [3 4 5 6]
  [5 6 7 8]
  [7 8 2 1]]]
3


In [11]:
arr6 = np.array([1,2,3,4,5], ndmin=5)     # 5 dimension array
print(arr6)
print(type(arr6))
print(arr6.ndim)

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>
5


# NumPy Array Indexing 

In [12]:
# Array indexing is the same as accessing an array element. you can access array by element
# by refering to its index element The Index in numpy starts with 0.

In [13]:
# 1D array
arr7 = np.array([1,2,3,4,5])
print(arr7[0])
print(arr7[4])

1
5


In [14]:
#1D array
arr8 = np.array([1,2,3,4,5,6,7,8,9,10])
a= arr8[2]    # 3 
print("The fisrt element is ", a)
b= arr8[4]    # 5
print("The second element is ", b)
c= arr8[8]    # 9
print("The third element is ", c)
d = a+b+c
print("The sum of the number is ", d)

The fisrt element is  3
The second element is  5
The third element is  9
The sum of the number is  17


In [15]:
# 2D array
arr9 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr9)
a1 = arr9[0][1]
print("The fisrt row and 2nd element ", a1)
b1 = arr9[0][4]
print("The first row and 5th element ", b1)
c1 = arr9[1][3]
print("The second row and 4th element ", c1)
d1 = arr9[0][1]+arr9[0][4]+arr9[1][3]
print("The sum is ", d1)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
The fisrt row and 2nd element  20
The first row and 5th element  50
The second row and 4th element  90
The sum is  160


In [4]:
# 3D array
arr10 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])

ar1 = arr10[0,0,0]
ar2 = arr10[0,0,1]
ar3 = arr10[0,0,2]
ar4 = arr10[0,0,3]

ar5 = arr10[0,1,0]
ar6 = arr10[0,1,1]
ar7 = arr10[0,1,2]
ar8 = arr10[0,1,3]

ar9 = arr10[0,2,0]
ar10 = arr10[0,2,1]
ar11 = arr10[0,2,2]
ar12 = arr10[0,2,3]

print(arr10)
print(ar1,ar2,ar3,ar4)
print(ar5,ar6,ar7,ar8)
print(ar9,ar10,ar11,ar12)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
1 2 3 4
5 6 7 8
9 10 11 12


# Slicing of NumPy Array

In [17]:
# 1D array slicing 
ay1 = np.array([1,2,3,4,5,6,7,8])
print(ay1)
print(ay1[2:6])
print(ay1[1:7])
print(ay1[::2])     # To skip one row 

[1 2 3 4 5 6 7 8]
[3 4 5 6]
[2 3 4 5 6 7]
[1 3 5 7]


In [5]:
# 2D array
ay2 = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(ay2)
print(ay2[0,1:4])
print("===========")
print(ay2[1,1:4])

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
[20 30 40]
[70 80 90]


In [19]:
# Data types in numpy 
'''
i-integer,
b-boolean, 
u-unsigned int , 
f-floating point, 
c-complex floating,
m -timedelta
M - datetime
O - object 
S - string 
U - unicode string 
V - Fixed chunk of memory for other type(void)
'''

'\ni-integer,\nb-boolean, \nu-unsigned int , \nf-floating point, \nc-complex floating,\nm -timedelta\nM - datetime\nO - object \nS - string \nU - unicode string \nV - Fixed chunk of memory for other type(void)\n'

In [6]:
# checking the data type in array
ay3 = np.array([1,2,3,4])
print(ay3.dtype)
print(type(ay3))
ay4 = np.array(["Sahil","Arpit","Harshit"])
print(ay4.dtype)

int32
<class 'numpy.ndarray'>
<U7


In [21]:
# creating datatype in numpy
ay5 = np.array([1,2,3,4],dtype='S')
print(ay5)
print(ay5.dtype)

[b'1' b'2' b'3' b'4']
|S1


# NumPy Array Shape

In [22]:
# Shape of array is the number of elemnet in each dimension.

In [23]:
arrr1 = np.array([[1,2,3,4,5,6],[5,6,7,8,9,7],[1,2,3,4,5,9]])
print(arrr1.shape)

(3, 6)


In [4]:
arrr2 = np.array([[[1,2,3,4,5,6,8],[5,6,7,8,9,7,9],[1,2,3,4,5,9,10],[1,2,3,4,5,6,4]]])
print(arrr2.shape)
print(arrr2.ndim)

(1, 4, 7)
3


# Joining NumPy Array

In [25]:
aay1 = np.array([1,2,3])
aay2 = np.array([4,5,6])
aay = np.concatenate((aay1,aay2))
print(aay)

[1 2 3 4 5 6]


In [4]:
aay3 = np.array([[1,2,3],[4,5,6]])
aay4 = np.array([[4,5,6],[9,8,7]])
aay = np.concatenate((aay3,aay4),axis=0)
print(aay)     # join along col

[[1 2 3]
 [4 5 6]
 [4 5 6]
 [9 8 7]]


In [27]:
aay3 = np.array([[1,2,3],[4,5,6]])
aay4 = np.array([[4,5,6],[9,8,7]])
aay = np.concatenate((aay3,aay4),axis=1)
print(aay)     # join along rows

[[1 2 3 4 5 6]
 [4 5 6 9 8 7]]


# Splitting NumPy Arrays

In [28]:
aay4 = np.array([1,2,3,4,5,6])
newarr = np.array_split(aay4,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [29]:
aay5 = np.array([1,2,3,4,5,6])
new_arr = np.array_split(aay5,4)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Ravel and Flatten
It will convert multidimensional array into 1D array. They both perform the same operation.

In [30]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("The dimension of array is ", m.ndim)
n= m.ravel()
print("It will change 3d array to 1d", n)
print("This is the 1d array", n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
The dimension of array is  3
It will change 3d array to 1d [1 2 3 4 5 6 7 8 9]
This is the 1d array 1


In [31]:
m1 = np.array([[[[1,2,3],[4,5,6],[7,8,9],[3,5,7]]]])
print(m1)
print("The dimension of array is ", m1.ndim)
n1= m.flatten()
print("It will change 3d array to 1d", n1)
print("This is the 1d array", n1.ndim)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]
   [3 5 7]]]]
The dimension of array is  4
It will change 3d array to 1d [1 2 3 4 5 6 7 8 9]
This is the 1d array 1


# Unique function

In [32]:
uni = np.array([1,1,1,2,2,2,5,5,5,66,6,66,6,66,3,3,3,3,12,12,12])
print(uni)
k = np.unique(uni)
print("These values are unique",k)     # remove the duplicate from the array.

[ 1  1  1  2  2  2  5  5  5 66  6 66  6 66  3  3  3  3 12 12 12]
These values are unique [ 1  2  3  5  6 12 66]


In [33]:
uni = np.array([1,1,1,2,2,2,5,5,5,66,6,66,6,66,3,3,3,3,12,12,12])
print(uni)
k = np.unique(uni,return_index = True)
print("These values are unique",k)

[ 1  1  1  2  2  2  5  5  5 66  6 66  6 66  3  3  3  3 12 12 12]
These values are unique (array([ 1,  2,  3,  5,  6, 12, 66]), array([ 0,  3, 14,  6, 10, 18,  9], dtype=int64))


In [34]:
uni = np.array([1,1,1,2,2,2,5,5,5,66,6,66,6,66,3,3,3,3,12,12,12])
print(uni)
k = np.unique(uni,return_index = True,return_counts = True)
print("These values are unique",k)

[ 1  1  1  2  2  2  5  5  5 66  6 66  6 66  3  3  3  3 12 12 12]
These values are unique (array([ 1,  2,  3,  5,  6, 12, 66]), array([ 0,  3, 14,  6, 10, 18,  9], dtype=int64), array([3, 3, 4, 3, 2, 3, 3], dtype=int64))


# Delete

In [7]:
dele = np.array([1,2,3,4,5,6])
d = np.delete(dele,[2])         # np.delete(array,index_value)
print(d)

[1 2 4 5 6]


# 100 NumPy Questions

In [36]:
# Import the numpy package under the name
import numpy as np

In [37]:
# Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2270588361616
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30153
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


In [38]:
# Create a null vector of size 10 and update sixth value to 11
import numpy as np
vec = np.zeros(10)
print(vec)
vec[6] = 11
print(vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [39]:
#How to find the memory size of any array
print(id(vec))  # It will give the memory addess
print(vec.nbytes)
x = np.array([1,2,3,4])
print(x.nbytes)
print(x.size)
print("-------------------------------------------")
str = np.array(["Sahil","harshit","Arpit"])
print(str.nbytes) # provide the size of memeory take by that particular list.
print(str.size)   # No of element present in list.


2711185094480
80
16
4
-------------------------------------------
84
3


In [40]:
# How to get the documentation of the numpy add function from the command line? 
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [41]:
# Create a vector with values ranging from 10 to 49 and remove 1st and last element in list 
values = np.arange(10,49)
print(values)
print("---------------------")
val = values[1:-1]
print(val)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
---------------------
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [42]:
# Reverse a vector (first element becomes last)
vec1 = np.arange(10,20)
print(vec1)
print("-------------")
x1 = vec1[::-1]   # Reverse the vector
print(x1)

[10 11 12 13 14 15 16 17 18 19]
-------------
[19 18 17 16 15 14 13 12 11 10]


In [43]:
# Create a 3x3 matrix with values ranging from 1 to 8
mat = np.arange(1,10).reshape(3,3)
print(mat)
print(mat.ndim)
print(mat.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
int32


In [44]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
ind = np.array([1,2,0,0,4,0])
new_ind = []
def indices_print(indi):
    for i in indi:
        if i != 0:
            new_ind.append(i)
        else:
            print("")
    return new_ind
indie_print = indices_print(ind)
print(indie_print)




[1, 2, 4]


In [45]:
# Create a 3x3 identity matrix

In [46]:
identity = np.identity(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
# Create a 3x3x3 array with random values
rand = np.random.random((3,3))
print(rand)
print(rand.dtype)
print(rand.ndim)

[[0.71700069 0.84019746 0.53460897]
 [0.59614178 0.70136497 0.96860736]
 [0.45468428 0.45155666 0.36448508]]
float64
2


In [48]:
rand1 = np.random.random((3,3,3))
print(rand1)
print(rand1.dtype)
print(rand1.ndim)

[[[0.47851688 0.45721295 0.63485498]
  [0.87629674 0.43867435 0.94309435]
  [0.22673435 0.73576389 0.89628878]]

 [[0.38051802 0.16764791 0.72036412]
  [0.84522715 0.5304551  0.31385963]
  [0.37036889 0.58452071 0.15727531]]

 [[0.58913294 0.91461203 0.21017233]
  [0.56152276 0.00732049 0.28725565]
  [0.56247642 0.91341964 0.25077408]]]
float64
3


In [49]:
# Create a 10x10 array with random values and find the minimum and maximum values
arr_rand = np.random.random((10,10))
mini,maxi = arr_rand.min(),arr_rand.max()
print(arr_rand)
print("The maximum number is {} and minimum number is {}".format(maxi,mini))
print(arr_rand.dtype)
print(arr_rand.ndim)

[[0.70553336 0.54076616 0.53772801 0.70983362 0.35247546 0.63285527
  0.60956371 0.29429852 0.05020152 0.86646889]
 [0.35492317 0.98109588 0.19346482 0.19252979 0.52301768 0.0804206
  0.07359361 0.91902409 0.66492627 0.91827033]
 [0.96665236 0.34139206 0.44791007 0.35508135 0.93282735 0.28114779
  0.37447561 0.80659417 0.60191799 0.67531813]
 [0.62055063 0.43611928 0.48254721 0.44654434 0.99279692 0.42518815
  0.07254531 0.1773062  0.42908369 0.74416444]
 [0.80430567 0.09885332 0.08871869 0.79904037 0.54896229 0.43383044
  0.5345269  0.40745665 0.51046553 0.64531522]
 [0.40607597 0.41876583 0.23423395 0.98247142 0.63375992 0.09069096
  0.45359423 0.47921941 0.1692087  0.76445917]
 [0.49357379 0.21213715 0.6911624  0.08474999 0.11457676 0.99253148
  0.96678309 0.62272406 0.68423739 0.31687879]
 [0.03989646 0.96355337 0.53127989 0.29599207 0.21248109 0.00493968
  0.42551893 0.51855853 0.27070378 0.80495504]
 [0.28857913 0.81231229 0.51249127 0.92032009 0.16572787 0.0069407
  0.51483873 0

In [50]:
# Create a random vector of size 30 and find the mean value
rand_vec = np.random.random(30)
mean = rand_vec.mean()
print(rand_vec)
print("-------------")
print("The mean is ", mean)

[0.35822128 0.0105327  0.8127171  0.48834745 0.27331927 0.72374046
 0.68596105 0.27115714 0.04460771 0.76802405 0.71626897 0.47557994
 0.76949484 0.31412748 0.74451314 0.04827453 0.41090309 0.82747994
 0.71333642 0.60589928 0.51702206 0.94199458 0.02816026 0.05032321
 0.19181246 0.63348923 0.44011844 0.74329703 0.50099043 0.59371986]
-------------
The mean is  0.4901144469467657


In [5]:
# Create a 2d array with 1 on the border and 0 inside 
import numpy as np
arr_one = np.ones((5,5))
arr_one[1:-1,1:-1] = 0
print(arr_one)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [52]:
# How to add a border (filled with 0's) around an existing array?
arr_one = np.ones((5,5))
arr_one[0:1] = 0
arr_one[4:]= 0
arr_one[1,0],arr_one[2,0],arr_one[3,0]=0,0,0
arr_one[1,4],arr_one[2,4],arr_one[3,4]=0,0,0
print(arr_one)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [53]:
# How to add a border (filled with 0's) around an existing array?
# We do padding to include 0 in our array.
arr_zero = np.ones((3,3))
print(arr_zero)
print("--------------------")
arr_z= np.pad(arr_zero,pad_width=1,mode='constant', constant_values=0)
print(arr_z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
--------------------
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [54]:
# What is the result of the following expression
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [55]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
diag1 = np.diag((1,2,3,4,5))
print(diag1)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [56]:
# Create a 8x8 matrix and fill it with a checkerboard pattern
     # 1,3,5,7 row is changed
# check_board: This is the NumPy array we created earlier to represent the chessboard.
#[1::2, ::2]: This part specifies the rows and columns where we want to assign the value 1.

# 1::2: This specifies the row slicing. It starts from the second row (index 1) 
# and selects every other row (stride 2). 
# So it selects rows 1, 3, 5, and 7 (because indexing starts from 0).

# ::2: This specifies the column slicing. 
# It selects every other column starting from the first column (index 0). 
# So it selects columns 0, 2, 4, and 6.

# =1: This assigns the value 1 to the selected rows and columns.
# Syntax of slicing in numpy 
# array[row_start:row_stop:row_step, col_start:col_stop:col_step]   very important synatx

check_board = np.zeros((8,8))
check_board[1::2,::2]=1 
check_board[::2,1::2]=1
print(check_board)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [57]:
check_board1 = np.zeros((8,8))
check_board1[1::2,::2]=1
check_board1[::2,1::2]=1
print(check_board1)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [58]:
# Create a checkerboard 8x8 matrix using the tile function
tile_arr = np.tile([[0,1],[1,0]],(4,4))
print(tile_arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
array_shape = np.arange(1,337).reshape(6,7,8)
print(array_shape)
flat_index = 100
shape = array_shape.shape
index = np.unravel_index(flat_index,shape)
print(index)
print("The dimesnion of array",array_shape.ndim)

[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220 221

In [60]:
# unravel_index = It will basically convert a flat array into a multidimesional array. and return the 
# the value of index for a particular element in the array.
import numpy as np
# Create a 2D array with shape (3, 4)
arr = np.arange(12).reshape(3, 4)
print(arr)
# Flat index
flat_index = 6
# Shape of the array
shape = arr.shape
# Convert flat index to multi-dimensional indices
indices = np.unravel_index(flat_index, shape)
print(indices)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(1, 2)


In [61]:
# What is Normalizing a maxtric and how can we normalize a 5,5 matrix.

In [62]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
matrix1 = np.random.random((5,3))
matrix2 = np.random.random((3,2))
matrix_sol = np.dot(matrix1,matrix2)
print(matrix_sol)

[[0.04881169 0.61819121]
 [0.50154607 1.56268497]
 [0.16444253 0.74314507]
 [0.60034936 1.89775558]
 [0.32626943 1.21587686]]


In [63]:
# Given a 1D array, negate all elements which are between 3 and 8, in place
negate_ele = np.arange(11)
negate_ele[(3<negate_ele) & (negate_ele<=8)] *= -1
print(negate_ele)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [64]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [65]:
#How to round away from zero a float array ?
round_array = np.array([1,2.4,3,4,5])
rnd = np.round(round_array)
print(rnd)

[1. 2. 3. 4. 5.]


In [66]:
# How to find common values between two arrays?
common_array1 = np.array([1,2,3,4,5,6])
common_array2 = np.array([2,3,4])
intersection = np.intersect1d(common_array1,common_array2)
print(intersection)

[2 3 4]


In [67]:
# How to get the dates of yesterday, today and tomorrow?
yesterday = np.datetime64('today','D')-np.timedelta64(1,'D')
today = np.datetime64('today','D')
tommorow = np.datetime64('today','D')+np.timedelta64(1,'D')
print(today)
print(yesterday)
print(tommorow)

2024-05-08
2024-05-07
2024-05-09


In [68]:
# How to get all the dates corresponding to the month of July 2016?
all_date = np.arange('2016-06','2016-07',dtype = 'datetime64[D]')
print(all_date)

['2016-06-01' '2016-06-02' '2016-06-03' '2016-06-04' '2016-06-05'
 '2016-06-06' '2016-06-07' '2016-06-08' '2016-06-09' '2016-06-10'
 '2016-06-11' '2016-06-12' '2016-06-13' '2016-06-14' '2016-06-15'
 '2016-06-16' '2016-06-17' '2016-06-18' '2016-06-19' '2016-06-20'
 '2016-06-21' '2016-06-22' '2016-06-23' '2016-06-24' '2016-06-25'
 '2016-06-26' '2016-06-27' '2016-06-28' '2016-06-29' '2016-06-30']


In [69]:
# How to compute ((A+B)*(-A/2)) in place (without copy)
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*-1
D = np.add(A,B)
E = np.divide(A,2)
F = np.negative(E)
G = np.multiply(D,F)
print(G)

[-1.5 -1.5 -1.5]


In [70]:
# Create a 5x5 matrix with row values ranging from 0 to 4 
mat_zero = np.zeros((5,5))
mat_range = np.arange(5) + mat_zero
print(mat_range)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [71]:
# Create a random vector of size 10 and sort it
rand_vector = np.random.random(10)
rv1 = sort(rand_vector)
print(rv1)

[0.08328576 0.20926829 0.21699549 0.25474045 0.34293752 0.38738296
 0.71310382 0.83800466 0.87547237 0.95569757]


In [95]:
# Consider two random array A and B, check if they are equal
random_a = np.random.randint(0,2,6)
random_b = np.random.randint(0,2,6)
print("The first array is ",random_a)
print("The first array is ",random_b)
array_equal = np.allclose(random_a,random_b)
print(array_equal)

The first array is  [1 1 0 1 1 0]
The first array is  [0 0 1 0 1 1]
False
